services:
  - type: web
    name: kitap-takip
    runtime: node
    plan: free
    buildCommand: cd frontend && npm install --include=dev && npm run build
    startCommand: cd backend && node index.js
    envVars:
      - key: NODE_ENV
        value: production
